# Generated by Django 5.2.2 on 2025-06-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('achievement_name', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('images', models.FileField(upload_to='achievements/')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
