# Generated by Django 5.2.2 on 2025-06-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='achievement',
            table='achievements',
        ),
    ]
