# Generated by Django 5.2.2 on 2025-06-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0002_alter_achievement_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='images',
            new_name='file',
        ),
    ]
