# Generated by Django 5.2.2 on 2025-06-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_rename_images_achievement_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='achievement_name',
            new_name='description',
        ),
    ]
