# Generated by Django 5.2.2 on 2025-06-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0004_rename_achievement_name_achievement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='图标类名')),
                ('color', models.CharField(choices=[('blue', '蓝色'), ('green', '绿色'), ('purple', '紫色'), ('yellow', '黄色'), ('red', '红色'), ('indigo', '靛蓝')], default='blue', max_length=20, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('created_by', models.CharField(max_length=100, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '成果分类',
                'verbose_name_plural': '成果分类',
                'db_table': 'category',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='type',
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(default='其他', max_length=100, verbose_name='成果的类型'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='获取时间'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.CharField(max_length=100, verbose_name='成果描述'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='file',
            field=models.FileField(default='achievements/none.png', upload_to='achievements/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='username',
            field=models.CharField(max_length=100, verbose_name='逻辑外键用户名'),
        ),
    ]
