# Generated by Django 5.2.2 on 2025-06-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0005_category_remove_achievement_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
