# Generated by Django 5.2.2 on 2025-06-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0006_alter_category_options_remove_category_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
    ]
