# Generated by Django 5.2.2 on 2025-06-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0007_remove_category_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='成果名'),
        ),
    ]
