# Generated by Django 5.2.2 on 2025-06-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0008_achievement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='datetime',
            field=models.DateTimeField(verbose_name='获取时间'),
        ),
    ]
