# Generated by Django 5.2.2 on 2025-06-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_avatar_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_public',
        ),
    ]
