# Generated by Django 5.2.2 on 2025-06-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_public',
            new_name='is_published',
        ),
    ]
